### ISSUE TITLE
모델 다운로드가 실패합니다

### ISSUE THREAD

**Issue by hyunki** [Daniel-Heo/realtrans#59]
안녕하세요 
파이썬설치 에러가 나서 3.12.8 virtualenv로 설치를 했습니다.
Requirements installed successfully 라는 화면이 뜨고 
virtualenv 환경 커맨드콘솔에서 realtrans.exe를 실행하였습니다.

![image](https://github.com/user-attachments/assets/ce1dde19-f5a6-4587-8417-5d92a89d9056)
이 화면처럼 허깅페이스 트랜스포머 워닝이 뜨고 1시간 정도 기다려봤는데
아래와 같은 에러가 발생합니다. 

Fetching 4 files:  25%|##5       | 1/4 [03:47<11:22, 227.43s/it]
Exception in thread 
Thread-1 (main):
Traceback (most recent call last):
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\urllib3\response.py", line 748, in _error_catcher

    
yield
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\urllib3\response.py", line 894, in _raw_read

    
raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
urllib3.exceptions
IncompleteRead
: 
IncompleteRead(208452608 bytes read, 29705290 more expected)
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\requests\models.py", line 820, in generate

    
yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\urllib3\response.py", line 1060, in stream

    
data = self.read(amt=amt, decode_content=decode_content)
   
   
   
^^^^^^^^^
^^^^
^^^
^^^^^
^^^
^^^^^
^^
^^^^^^^^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\urllib3\response.py", line 977, in read

    
data = self._raw_read(amt)
  
  
    
^^^^^^^^
^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\urllib3\response.py", line 872, in _raw_read

    
with self._error_catcher():
 ^
^^^^^
^^
^^^
^^^^^
  File "C:\Users\whitg\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__

    
self.gen.throw(value)
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\urllib3\response.py", line 772, in _error_catcher

    
raise ProtocolError(arg, e) from e
urllib3.exceptions
ProtocolError
: 
('Connection broken: IncompleteRead(208452608 bytes read, 29705290 more expected)', IncompleteRead(208452608 bytes read, 29705290 more expected))
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\whitg\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner

    
self.run()
  File "C:\Users\whitg\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run

    
self._target(*self._args, **self._kwargs)
  File "C:\RealTrans_2.1.14\runTransWin.py", line 371, in main

    
ctrans_manager.check_fwmodel(model_size)
  File "C:\RealTrans_2.1.14\lib\ctrans_manager.py", line 426, in check_fwmodel

    
ret=huggingface_hub.snapshot_download(repo_id, resume_download=True, **kwargs)
^^^
^^
^^^^^
^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^
^^^^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn

    
return fn(*args, **kwargs)
           ^^^^^^
^^^
^^^^^^

  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 293, in snapshot_download

    
thread_map(
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map

    
return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  
     
^^^
^^^
^^^^^^^^^^^^^
^^
^^^
^^^^^
^^^
^^^
^^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map

    
return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))

  
^^
^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^
^^^^^^^
^^^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\tqdm\std.py", line 1181, in __iter__

    
for obj in iterable:

        
^^^

  File "C:\Users\whitg\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 619, in result_iterator

    
yield _result_or_cancel(fs.pop())
      
 ^^^^^^^
^^^^
^^
^^^

  File "C:\Users\whitg\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel

    
return fut.result(timeout)

  
     ^
^^^
^^
^^^
^^^^^^^
  File "C:\Users\whitg\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 456, in result

    
return self.__get_result()
    
   
^^
^^^^^^^^^^
  File "C:\Users\whitg\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result

    
raise self._exception
  File "C:\Users\whitg\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 59, in run

    
result = self.fn(*self.args, **self.kwargs)
^^^^^
^^^^^
^^^^
^^
^^^^^^^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\huggingface_hub\_snapshot_download.py", line 267, in _inner_hf_hub_download

    
return hf_hub_download(
  
      
^^
^^^^^^
^^^^
^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn

    
return fn(*args, **kwargs)
   
  
^^
^^^
^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download

    
return _hf_hub_download_to_cache_dir(
  
    
^^^
^^^
^^^^^^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\huggingface_hub\file_download.py", line 1011, in _hf_hub_download_to_cache_dir

    
_download_to_tmp_and_move(
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\huggingface_hub\file_download.py", line 1545, in _download_to_tmp_and_move

    
http_get(

  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\huggingface_hub\file_download.py", line 454, in http_get

    
for chunk in r.iter_content(chunk_size=constants.DOWNLOAD_CHUNK_SIZE):
  
   ^^^^^
^^
^^
^^
^^
^^^^^^
^^
  File "C:\RealTrans_2.1.14\virtualenv\Lib\site-packages\requests\models.py", line 822, in generate

    
raise ChunkedEncodingError(e)
requests.exceptions
ChunkedEncodingError
: 
('Connection broken: IncompleteRead(208452608 bytes read, 29705290 more expected)', IncompleteRead(208452608 bytes read, 29705290 more expected))

재시작 하면 다시 아래와 같은 화면이 뜨며 멈춥니다.
![image](https://github.com/user-attachments/assets/3e9aff91-20cd-4be3-9595-f1c60ab12fac)

**Comment by Daniel-Heo** [comment]
이 에러는 Hugging Face Hub를 통해 파일을 다운로드하는 과정에서 requests 라이브러리가 데이터를 올바르게 수신하지 못했을 때 발생하는 **ChunkedEncodingError**와 관련이 있습니다. 에러의 주요 원인과 이를 해결할 수 있는 방법을 아래에 설명합니다.

>> 해결하는 방법은 이전 다운받은 모델을 지우고 새로 받는 법입니다. 
아래의 디렉토리에서 해당하는 모델 디렉토리를 삭제한 후에 다시 다운로드를 시행합니다.
C:\Users\<사용자명>\.cache\huggingface\hub
같은 증상이 반복될 경우에 시스템적인 문제일수도 있습니다.

에러 분석
1. requests.exceptions.ChunkedEncodingError
이 에러는 서버에서 데이터를 청크(chunk, 작은 조각들) 단위로 보내는 중 연결이 끊겼거나, 데이터를 완전히 수신하지 못했을 때 발생합니다.
메시지에 따르면:
읽은 데이터: 208,452,608 바이트
예상했던 데이터: 추가로 29,705,290 바이트가 더 있어야 했지만, 수신되지 않음.
2. 에러 발생 위치
에러는 Hugging Face Hub의 http_get 함수 내에서 발생.
http_get 함수는 파일을 다운로드하기 위해 requests의 iter_content 메서드를 사용하여 데이터를 청크 단위로 읽음.
다운로드 도중 연결이 끊기거나 네트워크 상태가 불안정하여 IncompleteRead 예외가 발생.
에러 원인
1. 네트워크 문제
불안정한 인터넷 연결로 인해 데이터가 전송 도중 중단되었을 가능성.
서버와의 연결 시간이 초과되거나, 과도한 네트워크 트래픽이 문제를 야기.
2. 서버 문제
Hugging Face Hub의 서버 상태가 일시적으로 불안정했을 가능성.
요청량이 많거나 서버가 과부하 상태일 수 있음.
3. HTTP 요청 설정 문제
requests 라이브러리의 timeout 값이 너무 짧게 설정되었거나, 재시도 메커니즘이 없을 경우.
다운로드가 대용량 파일이라 시간이 오래 걸릴 때 발생 가능.
4. 파일 손상 또는 부분 다운로드
다운로드 중 일부 청크 데이터가 손상되었거나 누락되었을 수 있음.

**Comment by Daniel-Heo** [comment]
lib/ctrans_manager.py의 141번째 줄의 아래 부분 밑에 한줄을 추가해서 resume을 끄셔도 됩니다.
def _download_model(self, repo_id, resume=False):
   resume = False

**Comment by hyunki** [comment]
감사합니다. 우러전 영상 보는데 내용이 너무 궁금했어요!
